# Generated by Django 4.2.7 on 2023-12-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDlogger', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Completed', 'Completed')], default='Incomplete', max_length=20),
        ),
    ]
